# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: CI
on:
  pull_request:
    branches:
      - main
    
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        nodejs-version: [10, 12, 14, 16, 17]
        npm-version: [0, 6, 7, 8]
        exclude:
          - nodejs-version: 10
            npm-version: 8
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodejs-version }}
      - name: Update NPM
        if: matrix.npm-version != 0
        run: npm install --global npm@${{ matrix.npm-version }}
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm test
